# Generated by Django 4.2.3 on 2023-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(default='seuemail@sci.com.br', max_length=254),
        ),
    ]
