# Generated by Django 4.2.3 on 2023-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('ingresso', 'Ingresso'), ('vestuario', 'Vestuário')], default='alimento', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
