# Generated by Django 4.2.2 on 2023-06-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('produto', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
