# Generated by Django 4.2.1 on 2023-06-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_compras', '0002_itemcompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocompra',
            name='produto',
        ),
    ]
