# Generated by Django 4.2.1 on 2023-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('registro_de_compras', '0003_remove_registrocompra_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocompra',
            name='produto',
            field=models.ManyToManyField(through='registro_de_compras.ItemCompra', to='produtos.produto'),
        ),
    ]
