# Generated by Django 4.2.1 on 2023-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_compras', '0004_registrocompra_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
