# Generated by Django 4.2.1 on 2023-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_compras', '0005_alter_itemcompra_quantidade_alter_itemcompra_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocompra',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
